/*
 * The contents of this file are subject to the Mozilla Public
 * License Version 1.1 (the "MPL"); you may not use this file
 * except in compliance with the MPL. You may obtain a copy of
 * the MPL at http://www.mozilla.org/MPL/
 * 
 * Software distributed under the MPL is distributed on an "AS
 * IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the MPL for the specific language governing
 * rights and limitations under the MPL.
 * 
 * The Original Code is protoZilla.
 * 
 * The Initial Developer of the Original Code is Ramalingam Saravanan.
 * Portions created by Ramalingam Saravanan <svn@xmlterm.org> are
 * Copyright (C) 2001 Ramalingam Saravanan. All Rights Reserved.
 * 
 * Contributor(s):
 * 
 * Alternatively, the contents of this file may be used under the
 * terms of the GNU General Public License (the "GPL"), in which case
 * the provisions of the GPL are applicable instead of
 * those above. If you wish to allow use of your version of this
 * file only under the terms of the GPL and not to allow
 * others to use your version of this file under the MPL, indicate
 * your decision by deleting the provisions above and replace them
 * with the notice and other provisions required by the GPL.
 * If you do not delete the provisions above, a recipient
 * may use your version of this file under either the MPL or the
 * GPL.
 */

#include "nsISupports.idl"

%{C++

#define NS_PROCESSINFO_CLASSNAME  "ProcessInfo"
#define NS_PROCESSINFO_CONTRACTID "@mozilla.org/xpcom/process-info;1"

#define NS_PROCESSINFO_CID                     \
{ /* a54dbb90-38f8-11d5-8f42-006008948af5 */         \
   0xa54dbb90, 0x38f8, 0x11d5,                       \
    {0x8f, 0x42, 0x00, 0x60, 0x08, 0x94, 0x8a, 0xf5} }

%}

/**
 * System environment service.
 * 
 * At present, a thin wrapper around PR_GetEnv.
 */

[scriptable, uuid(a2fb4fa0-38f8-11d5-8f42-006008948af5)]
interface nsIProcessInfo : nsISupports
{
  /**
   * Returns value of specified environment variable,
   * or null string if variable is not defined.
   */
    string getEnv(in string name);
};

///////////////////////////////////////////////////////////////////////////////
