#include "nsISupports.idl"

[scriptable, uuid(fa6b4f61-5828-4e15-aebb-02d8dbfa689f)]
interface IFireGPGCall : nsISupports
{
  string Call(in string path, in string  parameters, in string sdin);
};
